{
  "category": "coding",
  "imageSrc": "https://theaipaper.b-cdn.net/articles/exception-handling-in-java.png",
  "imageSrcBase64": "data:image/png;base64,UklGRnQAAABXRUJQVlA4IGgAAACQAgCdASoKAAoAAUAmJbACdLoB+AADT3Rw8UtvAAD+56ez7vuwQf5TgS8Tx0BFrFc2QzHL5I9vf8vHuDXo/cFJP/clNcJFBDfq0Prs/69v7fvxv8/8f7+LvCPEk/n5FjVHuYaBew0AAA==",
  "createdAt": "2022-10-01T11:15:05.374Z",
  "updatedAt": "2022-10-01T11:15:05.374Z",
  "slug": "manejo-de-excepciones-en-java",
  "locale": "es",
  "categoryLocal": "codificación",
  "title": "Manejo de excepciones en Java",
  "summary": "El uso de bloques try-catch es la forma recomendada de manejar excepciones en Java. Las palabras clave marcadas y no marcadas se usan cuando espera que un método arroje una excepción. El bloque finalmente se utiliza para realizar cualquier tarea de limpieza que deba realizarse independientemente de la ruta de ejecución. Las excepciones se esperan y son generadas por la aplicación, mientras que los errores generalmente se manejan con controladores de excepciones. Este artículo le enseñará sobre el manejo de excepciones en Java y cómo puede manejar las excepciones en su código. Es crucial que los programadores entiendan cómo funcionan las excepciones en Java.",
  "intro": {
    "compiledSource": "var l=Object.defineProperty,m=Object.defineProperties;var d=Object.getOwnPropertyDescriptors;var c=Object.getOwnPropertySymbols;var s=Object.prototype.hasOwnProperty,t=Object.prototype.propertyIsEnumerable;var i=(e,a,o)=>a in e?l(e,a,{enumerable:!0,configurable:!0,writable:!0,value:o}):e[a]=o,r=(e,a)=>{for(var o in a||(a={}))s.call(a,o)&&i(e,o,a[o]);if(c)for(var o of c(a))t.call(a,o)&&i(e,o,a[o]);return e},p=(e,a)=>m(e,d(a));var u=(e,a)=>{var o={};for(var n in e)s.call(e,n)&&a.indexOf(n)<0&&(o[n]=e[n]);if(e!=null&&c)for(var n of c(e))a.indexOf(n)<0&&t.call(e,n)&&(o[n]=e[n]);return o};const layoutProps={},MDXLayout=\"wrapper\";function MDXContent(o){var n=o,{components:e}=n,a=u(n,[\"components\"]);return mdx(MDXLayout,p(r(r({},layoutProps),a),{components:e,mdxType:\"MDXLayout\"}),mdx(\"p\",null,`En programaci\\xF3n, nada puede ser 100% perfecto. Siempre habr\\xE1 alg\\xFAn tipo de error o evento inesperado que pueda ocurrir durante la ejecuci\\xF3n de un programa. Estos problemas se conocen como \"excepciones\" y pueden tomar muchas formas. Por ejemplo, una excepci\\xF3n podr\\xEDa ser algo como leer una variable de cadena vac\\xEDa, intentar acceder al sexto elemento de una matriz con solo cinco elementos, o incluso algo tan simple como no tener suficiente memoria disponible para continuar ejecutando instrucciones.\nEstas circunstancias excepcionales se denominan excepciones porque son excepcionales y el controlador del programa no puede continuar con su ruta de ejecuci\\xF3n habitual m\\xE1s. Para el usuario, parece como si la aplicaci\\xF3n hubiera fallado \"excepcionalmente\" de alguna manera y necesita recuperarse de este estado. Por lo tanto, contamos con manejo de excepciones en Java para manejar estos casos extremos con gracia para que nuestras aplicaciones sigan funcionando correctamente a pesar de ellos. En esta publicaci\\xF3n de blog, aprender\\xE1 sobre varios tipos de excepciones en Java y c\\xF3mo podemos manejarlas usando bloques try-catch de manera efectiva.`))}MDXContent.isMDXComponent=!0;\n",
    "scope": {}
  },
  "content": {
    "compiledSource": "var d=Object.defineProperty,t=Object.defineProperties;var m=Object.getOwnPropertyDescriptors;var s=Object.getOwnPropertySymbols;var c=Object.prototype.hasOwnProperty,i=Object.prototype.propertyIsEnumerable;var p=(e,a,n)=>a in e?d(e,a,{enumerable:!0,configurable:!0,writable:!0,value:n}):e[a]=n,r=(e,a)=>{for(var n in a||(a={}))c.call(a,n)&&p(e,n,a[n]);if(s)for(var n of s(a))i.call(a,n)&&p(e,n,a[n]);return e},l=(e,a)=>t(e,m(a));var u=(e,a)=>{var n={};for(var o in e)c.call(e,o)&&a.indexOf(o)<0&&(n[o]=e[o]);if(e!=null&&s)for(var o of s(e))a.indexOf(o)<0&&i.call(e,o)&&(n[o]=e[o]);return n};const layoutProps={},MDXLayout=\"wrapper\";function MDXContent(n){var o=n,{components:e}=o,a=u(o,[\"components\"]);return mdx(MDXLayout,l(r(r({},layoutProps),a),{components:e,mdxType:\"MDXLayout\"}),mdx(\"h2\",null,\"\\xBFQu\\xE9 es el manejo de excepciones en Java?\"),mdx(\"p\",null,\"Cuando una aplicaci\\xF3n Java encuentra un problema que le impide continuar con su ejecuci\\xF3n, genera una excepci\\xF3n. Estas excepciones son lanzadas por la aplicaci\\xF3n, capturadas por el entorno host, registradas y luego informadas al usuario.\"),mdx(\"h2\",null,\"Conceptos b\\xE1sicos de excepciones de Java\"),mdx(\"p\",null,\"Hay dos formas en las que puede manejar las excepciones en Java. El primero es usar bloques try-catch y el segundo es usar las palabras clave marcadas y no marcadas. El uso de bloques try-catch es la forma recomendada de manejar excepciones en Java.\"),mdx(\"p\",null,\"El bloque try-catch se usa cuando espera que su c\\xF3digo arroje una excepci\\xF3n. Codifica los bloques que podr\\xEDan arrojar excepciones dentro del bloque try y el c\\xF3digo que se ejecutar\\xE1 si no se arrojan excepciones dentro del bloque catch.\"),mdx(\"p\",null,\"Las palabras clave marcadas y no marcadas se usan cuando espera que un m\\xE9todo genere una excepci\\xF3n, pero se declara que el m\\xE9todo nunca arrojar\\xE1 una excepci\\xF3n. Usa la palabra clave marcada cuando llama a un m\\xE9todo que podr\\xEDa generar una excepci\\xF3n y usa la palabra clave no verificada cuando declara un m\\xE9todo que podr\\xEDa generar una excepci\\xF3n.\"),mdx(\"h2\",null,\"Excepciones marcadas y no marcadas\"),mdx(\"p\",null,'Por lo general, el entorno de tiempo de ejecuci\\xF3n de Java y el c\\xF3digo que escribe generan excepciones, pero las excepciones que genera el entorno de tiempo de ejecuci\\xF3n de Java se denominan \"excepciones verificadas\", mientras que las excepciones que genera su c\\xF3digo se denominan \"excepciones no verificadas\". . Puede usar las palabras clave marcadas y no marcadas para especificar si sus m\\xE9todos pueden generar excepciones marcadas o no marcadas.'),mdx(\"p\",null,\"Si la firma de un m\\xE9todo no especifica qu\\xE9 excepciones lanza, se supone que el m\\xE9todo lanza todas las excepciones marcadas. Si la firma de un m\\xE9todo especifica que no lanza excepciones verificadas, entonces se asume que todas las excepciones que el m\\xE9todo podr\\xEDa lanzar no est\\xE1n verificadas.\"),mdx(\"h2\",null,\"Diferencias de errores y excepciones\"),mdx(\"p\",null,\"Hay algunas diferencias sutiles pero significativas entre errores y excepciones. Por un lado, las excepciones se representan como instancias de una subclase de excepci\\xF3n de Java espec\\xEDfica, mientras que los errores se representan como una instancia de una subclase Error o una instancia de una subclase RuntimeException.\"),mdx(\"p\",null,\"Se esperan excepciones y las genera la aplicaci\\xF3n, mientras que los errores son inesperados y normalmente los crea el entorno de tiempo de ejecuci\\xF3n de Java. Las excepciones se representan como objetos, mientras que los errores se representan como tipos primitivos. El entorno de tiempo de ejecuci\\xF3n de Java registra los errores, mientras que la aplicaci\\xF3n o el entorno de tiempo de ejecuci\\xF3n de Java pueden registrar las excepciones. Las excepciones se manejan con bloques try-catch, mientras que los errores generalmente se manejan con controladores de excepciones.\"),mdx(\"h2\",null,\"Lanzar y lanzar excepciones\"),mdx(\"p\",null,\"Cuando se llama a un m\\xE9todo, podr\\xEDa generar una excepci\\xF3n si tiene el potencial para hacerlo. Para lanzar una excepci\\xF3n, usamos la palabra clave throw seguida del objeto de excepci\\xF3n que queremos lanzar. Tambi\\xE9n podr\\xEDamos crear nuestros propios objetos de excepci\\xF3n personalizados extendiendo la clase Exception.\"),mdx(\"p\",null,\"La palabra clave throw se puede usar con el bloque try o catch. Si se llama a un m\\xE9todo y se espera que genere una excepci\\xF3n, pero el m\\xE9todo no la gener\\xF3, entonces puede usar la palabra clave throw para generar la excepci\\xF3n esperada.\"),mdx(\"h2\",null,\"Java finalmente bloque: c\\xF3mo manejar finalmente\"),mdx(\"p\",null,'Notar\\xE1s que tenemos el bloque \"finally\" al final de nuestros ejemplos de bloques \"try-catch\". El bloque finalmente siempre se ejecuta y se garantiza que se ejecutar\\xE1 tanto si la aplicaci\\xF3n lanza una excepci\\xF3n como si no.'),mdx(\"p\",null,\"El bloque finalmente se utiliza para realizar cualquier tarea de limpieza que deba realizarse independientemente de la ruta de ejecuci\\xF3n. Puede usar el bloque finalmente para cerrar una conexi\\xF3n de base de datos, borrar una secuencia o registrar una excepci\\xF3n.\"),mdx(\"h2\",null,\"Conclusi\\xF3n\"),mdx(\"p\",null,\"Las excepciones son una parte importante de la programaci\\xF3n que no puede evitar. Es crucial que los programadores entiendan c\\xF3mo funcionan las excepciones en Java. Este art\\xEDculo le ense\\xF1ar\\xE1 sobre el manejo de excepciones en Java y c\\xF3mo puede manejar las excepciones en su c\\xF3digo. Adem\\xE1s, tambi\\xE9n aprender\\xE1 a crear sus propias excepciones personalizadas en Java.\"))}MDXContent.isMDXComponent=!0;\n",
    "scope": {}
  }
}